### ISSUE TITLE
第一课：使用 node 创建脚手架

### ISSUE THREAD

**Issue by luoxue-victor** [luoxue-victor/learn-node#1]
目录结构

**Comment by Tinolee615** [comment]
commander --> node.js命令行界面
inquirer --> 用户与命令行交互
metalsmith --> 静态模板处理
ejs、handlebars... --> 模板引擎
rimraf --> rm操作
lodash --> 字符串检查判断
minimatch --> 匹配字符串
iconv-lite --> 编码问题
download-git-repo --> 下载并提取git存储库(GitHub, GitLab, Bitbucket都)节点。
ora --> 加载等待的交互
chalk --> 终端显示效果美化
log-symbols --> 颜色的象征不同的日志级别
